/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as PosterRouteImport } from './routes/poster'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as TransformationsRouteImport } from './routes/transformations'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const PosterRoute = PosterRouteImport.update({
  id: '/poster',
  path: '/poster',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const TransformationsRoute = TransformationsRouteImport.update({
  id: '/transformations',
  path: '/transformations',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/poster': typeof PosterRoute
  '/reviews': typeof ReviewsRoute
  '/transformations': typeof TransformationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/poster': typeof PosterRoute
  '/reviews': typeof ReviewsRoute
  '/transformations': typeof TransformationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/poster': typeof PosterRoute
  '/reviews': typeof ReviewsRoute
  '/transformations': typeof TransformationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/poster' | '/reviews' | '/transformations'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/poster' | '/reviews' | '/transformations'
  id: '__root__' | '/' | '/about' | '/poster' | '/reviews' | '/transformations'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PosterRoute: typeof PosterRoute
  ReviewsRoute: typeof ReviewsRoute
  TransformationsRoute: typeof TransformationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poster': {
      id: '/poster'
      path: '/poster'
      fullPath: '/poster'
      preLoaderRoute: typeof PosterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transformations': {
      id: '/transformations'
      path: '/transformations'
      fullPath: '/transformations'
      preLoaderRoute: typeof TransformationsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PosterRoute: PosterRoute,
  ReviewsRoute: ReviewsRoute,
  TransformationsRoute: TransformationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
